spring.jpa.hibernate.ddl-auto= update
spring.datasource.url=jdbc:mariadb://192.168.56.103:3306/greenline
spring.datasource.username=lucas
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=true


server.port=8443
server.ssl.key-store=/etc/ssl/private/keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
server.ssl.key-password=changeit
server.ssl.key-alias=greenline.io